In [1]:
from utils import get_xlsx_files
import pandas as pd

data = pd.read_excel(get_xlsx_files()["多年模拟数据.xlsx"])

In [10]:
s = "2011年"
e = "2020年"

In [ ]:
data = data[[item for item in data.columns if item.endswith("年") and item >= s and item <= e]]

In [8]:
data

,2007年,2008年,2009年,2010年,2011年,2012年,2013年,2014年,2015年,2016年,2017年,2018年,2019年,2020年,2021年,2022年,2023年,2024年
0,0.31,0.344941,0.395718,0.369163,0.383563,0.389794,0.356069,0.354276,0.344240,0.338947,0.328814,0.322279,0.312193,0.292407,0.255780,0.307196,0.319182,0.317367
1,0.42,0.447310,0.444949,0.495357,0.556618,0.552158,0.558781,0.567176,0.550888,0.597995,0.673574,0.673970,0.727068,0.713612,0.708477,0.754848,0.710785,0.728689
2,0.31,0.333897,0.337617,0.346964,0.369982,0.331492,0.341550,0.322343,0.349223,0.387563,0.394178,0.419435,0.436346,0.490552,0.507847,0.450643,0.514166,0.548669
3,0.46,0.453317,0.497413,0.554493,0.536990,0.585413,0.617754,0.651244,0.657296,0.636693,0.652027,0.648681,0.670514,0.673653,0.674079,0.683607,0.632218,0.608419
4,0.95,0.935888,0.994558,0.990826,0.988423,1.031178,1.069261,1.026392,1.022606,1.021323,1.138367,1.069325,1.053276,1.126994,1.156239,1.136875,1.125939,1.146605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,0.52,0.506921,0.489615,0.515465,0.548943,0.524350,0.507696,0.483606,0.559377,0.594140,0.641328,0.657863,0.707940,0.659578,0.640553,0.612578,0.641337,0.653068
144,0.65,0.634976,0.618101,0.583873,0.526086,0.532021,0.543950,0.574972,0.621459,0.679196,0.675891,0.615589,0.640969,0.677006,0.703879,0.699048,0.662485,0.706796
145,0.58,0.611431,0.632922,0.619745,0.631978,0.708858,0.707289,0.682322,0.675115,0.670697,0.693648,0.736857,0.731569,0.737502,0.763754,0.762010,0.769953,0.774313
146,1.40,1.355731,1.399526,1.396410,1.418610,1.403466,1.410994,1.426122,1.393685,1.462352,1.486250,1.431399,1.453359,1.465159,1.424134,1.460087,1.501010,1.507964
147,0.62,0.643294,0.670362,0.695405,0.688184,0.732943,0.698526,0.659081,0.660309,0.727323,0.750891,0.801502,0.806500,0.828715,0.855677,0.854779,0.874112,0.934184

In [9]:
data.T.pct_change().T.iloc[:, 1:]

,2008年,2009年,2010年,2011年,2012年,2013年,2014年,2015年,2016年,2017年,2018年,2019年,2020年,2021年,2022年,2023年,2024年
0,0.112712,0.147207,-0.067106,0.039005,0.016246,-0.086521,-0.005036,-0.028328,-0.015377,-0.029895,-0.019874,-0.031295,-0.063376,-0.125262,0.201015,0.039018,-0.005685
1,0.065024,-0.005278,0.113290,0.123670,-0.008013,0.011994,0.015023,-0.028717,0.085511,0.126387,0.000588,0.078784,-0.018508,-0.007196,0.065452,-0.058374,0.025190
2,0.077089,0.011141,0.027684,0.066340,-0.104030,0.030341,-0.056236,0.083391,0.109786,0.017068,0.064077,0.040317,0.124228,0.035256,-0.112641,0.140961,0.067105
3,-0.014528,0.097274,0.114754,-0.031566,0.090175,0.055245,0.054214,0.009293,-0.031345,0.024084,-0.005132,0.033657,0.004681,0.000633,0.014135,-0.075173,-0.037643
4,-0.014855,0.062690,-0.003752,-0.002426,0.043255,0.036932,-0.040092,-0.003688,-0.001255,0.114600,-0.060650,-0.015008,0.069989,0.025950,-0.016747,-0.009620,0.018355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,-0.025153,-0.034138,0.052795,0.064947,-0.044800,-0.031760,-0.047451,0.156680,0.062145,0.079423,0.025783,0.076121,-0.068315,-0.028843,-0.043674,0.046947,0.018292
144,-0.023113,-0.026577,-0.055375,-0.098971,0.011281,0.022422,0.057030,0.080851,0.092906,-0.004866,-0.089218,0.041228,0.056224,0.039693,-0.006863,-0.052305,0.066887
145,0.054191,0.035149,-0.020820,0.019739,0.121650,-0.002213,-0.035299,-0.010562,-0.006544,0.034219,0.062293,-0.007176,0.008109,0.035596,-0.002283,0.010424,0.005662
146,-0.031621,0.032304,-0.002226,0.015897,-0.010675,0.005364,0.010722,-0.022745,0.049270,0.016342,-0.036906,0.015342,0.008119,-0.028000,0.025245,0.028028,0.004633
147,0.037571,0.042077,0.037358,-0.010384,0.065039,-0.046957,-0.056468,0.001863,0.101488,0.032404,0.067401,0.006236,0.027544,0.032535,-0.001049,0.022618,0.068723